name: Build and Commit PDF and PPTX

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Convert Markdown into HTML and PDF
        uses: KoharaKazuya/marp-cli-action@v3

      - name: Configure Git LFS
        run: |
          git config --global filter.lfs.required true
          git config --global filter.lfs.clean "git-lfs clean -- %f"
          git config --global filter.lfs.smudge "git-lfs smudge -- %f"
          git config --global filter.lfs.process "git-lfs filter-process"

      - name: Handle merge conflicts
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin ${{ github.head_ref }}
          git checkout -b temp-branch
          git add sample/index.pdf sample/index.pptx
          git rm --cached sample/index.pdf sample/index.pptx
          git add sample/index.pdf sample/index.pptx
          git lfs track "*.pdf" "*.pptx"
          git add .gitattributes

      - name: Commit and push changes
        run: |
          git add -A .
          git commit -m "PDF & PPTX generated by github actions"
          git push origin temp-branch:${{ github.head_ref }} -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
